# Generated by Django 3.0.8 on 2020-07-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('content', models.TextField(default='', verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('name', models.CharField(default='example.png', max_length=250, verbose_name='ファイル名')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='api.Memo')),
            ],
        ),
    ]
